CadastroAulas/Models/Aula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroAulas.Models
{
    public class Aula
    {
        [Key]
        public int Codcred { get; set; }
        public DateTime Data { get; set; }
        public string Turma { get; set; }
    }
}

CadastroAulas/Models/AulaAluno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroAulas.Models
{
    public class AulaAluno
    {
        [Key]
        public int key { get; set; }
        public String Aluno { get; set; }
        public int Codcred { get; set; }
    }
}

CadastroAulas/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CadastroAulas.Models;

namespace CadastroAulas.Models
{
    public class Contexto : DbContext
    {
        public DbSet<Aula> Aulas { get; set; }
        public Contexto(DbContextOptions<Contexto> opcoes) : base(opcoes) { }
        public DbSet<CadastroAulas.Models.AulaAluno> AulaAluno { get; set; }
    }
}

CadastroAulas/Models/ErrorViewModel.cs
using System;

namespace CadastroAulas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroAulas/Controllers/AulaAlunoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CadastroAulas.Models;

namespace CadastroAulas.Controllers
{
    public class AulaAlunoesController : Controller
    {
        private readonly Contexto _context;

        public AulaAlunoesController(Contexto context)
        {
            _context = context;
        }

        // GET: AulaAlunoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.AulaAluno.ToListAsync());
        }

        // GET: AulaAlunoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aulaAluno = await _context.AulaAluno
                .FirstOrDefaultAsync(m => m.key == id);
            if (aulaAluno == null)
            {
                return NotFound();
            }

            return View(aulaAluno);
        }

        // GET: AulaAlunoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AulaAlunoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("key,Aluno,Codcred")] AulaAluno aulaAluno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aulaAluno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aulaAluno);
        }

        // GET: AulaAlunoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aulaAluno = await _context.AulaAluno.FindAsync(id);
            if (aulaAluno == null)
            {
                return NotFound();
            }
            return View(aulaAluno);
        }

        // POST: AulaAlunoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("key,Aluno,Codcred")] AulaAluno aulaAluno)
        {
            if (id != aulaAluno.key)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aulaAluno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AulaAlunoExists(aulaAluno.key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aulaAluno);
        }

        // GET: AulaAlunoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aulaAluno = await _context.AulaAluno
                .FirstOrDefaultAsync(m => m.key == id);
            if (aulaAluno == null)
            {
                return NotFound();
            }

            return View(aulaAluno);
        }

        // POST: AulaAlunoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aulaAluno = await _context.AulaAluno.FindAsync(id);
            _context.AulaAluno.Remove(aulaAluno);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AulaAlunoExists(int id)
        {
            return _context.AulaAluno.Any(e => e.key == id);
        }
    }
}

CadastroAulas/Controllers/HomeController.cs
using CadastroAulas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroAulas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroAulas/Views/AulaAlunoes/Create.cshtml
@model CadastroAulas.Models.AulaAluno

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AulaAluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Aluno" class="control-label"></label>
                <input asp-for="Aluno" class="form-control" />
                <span asp-validation-for="Aluno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Codcred" class="control-label"></label>
                <input asp-for="Codcred" class="form-control" />
                <span asp-validation-for="Codcred" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroAulas/Views/AulaAlunoes/Index.cshtml
@model IEnumerable<CadastroAulas.Models.AulaAluno>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Aluno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Codcred)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Aluno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codcred)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.key">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.key">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.key">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CadastroAulas/Views/Aulas/Create.cshtml
@model CadastroAulas.Models.Aula

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turma" class="control-label"></label>
                <input asp-for="Turma" class="form-control" />
                <span asp-validation-for="Turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroAulas/Views/Aulas/Index.cshtml
@model IEnumerable<CadastroAulas.Models.Aula>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>
            <th>@Html.DisplayNameFor(model => model.Codcred)</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Turma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codcred)
            </td>
        </tr>
}
    </tbody>
</table>

CadastroAulas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CadastroAulas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroAulas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadastroAulas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AulaAlunoes" asp-action="Index">Cadastrar Aluno</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CadastroAulas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>